//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  blog: Blog;
  blogConnection: BlogConnection;
  projects: Projects;
  projectsConnection: ProjectsConnection;
  global: Global;
  globalConnection: GlobalConnection;
  theme: Theme;
  themeConnection: ThemeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryProjectsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryThemeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryThemeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ThemeFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  pages?: InputMaybe<PagesFilter>;
  blog?: InputMaybe<BlogFilter>;
  projects?: InputMaybe<ProjectsFilter>;
  global?: InputMaybe<GlobalFilter>;
  theme?: InputMaybe<ThemeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Pages | Blog | Projects | Global | Theme | Folder;

export type HomeSectionsHero = {
  __typename?: 'HomeSectionsHero';
  headline?: Maybe<Scalars['String']['output']>;
  subHeadline?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsMarqueeItems = {
  __typename?: 'HomeSectionsMarqueeItems';
  title?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsMarquee = {
  __typename?: 'HomeSectionsMarquee';
  items?: Maybe<Array<Maybe<HomeSectionsMarqueeItems>>>;
};

export type HomeSectionsFeatureItems = {
  __typename?: 'HomeSectionsFeatureItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  fimage?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsFeature = {
  __typename?: 'HomeSectionsFeature';
  items?: Maybe<Array<Maybe<HomeSectionsFeatureItems>>>;
};

export type HomeSectionsServicesItems = {
  __typename?: 'HomeSectionsServicesItems';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  serviceImage?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsServices = {
  __typename?: 'HomeSectionsServices';
  title?: Maybe<Scalars['String']['output']>;
  subTitle?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeSectionsServicesItems>>>;
};

export type HomeSectionsCallToActionActionLink = {
  __typename?: 'HomeSectionsCallToActionActionLink';
  text?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsCallToAction = {
  __typename?: 'HomeSectionsCallToAction';
  headline?: Maybe<Scalars['String']['output']>;
  actionLink?: Maybe<HomeSectionsCallToActionActionLink>;
};

export type HomeSectionsTestimonialsCustomers = {
  __typename?: 'HomeSectionsTestimonialsCustomers';
  name?: Maybe<Scalars['String']['output']>;
  job?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  testimonial?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsTestimonials = {
  __typename?: 'HomeSectionsTestimonials';
  title?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  customers?: Maybe<Array<Maybe<HomeSectionsTestimonialsCustomers>>>;
};

export type HomeSectionsProjects = {
  __typename?: 'HomeSectionsProjects';
  title?: Maybe<Scalars['String']['output']>;
};

export type HomeSectionsPosts = {
  __typename?: 'HomeSectionsPosts';
  title?: Maybe<Scalars['String']['output']>;
};

export type HomeSections = HomeSectionsHero | HomeSectionsMarquee | HomeSectionsFeature | HomeSectionsServices | HomeSectionsCallToAction | HomeSectionsTestimonials | HomeSectionsProjects | HomeSectionsPosts;

export type Home = Node & Document & {
  __typename?: 'Home';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<HomeSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeSectionsHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  subHeadline?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type HomeSectionsMarqueeItemsFilter = {
  title?: InputMaybe<StringFilter>;
};

export type HomeSectionsMarqueeFilter = {
  items?: InputMaybe<HomeSectionsMarqueeItemsFilter>;
};

export type HomeSectionsFeatureItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  fimage?: InputMaybe<ImageFilter>;
};

export type HomeSectionsFeatureFilter = {
  items?: InputMaybe<HomeSectionsFeatureItemsFilter>;
};

export type HomeSectionsServicesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  serviceImage?: InputMaybe<ImageFilter>;
};

export type HomeSectionsServicesFilter = {
  title?: InputMaybe<StringFilter>;
  subTitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  items?: InputMaybe<HomeSectionsServicesItemsFilter>;
};

export type HomeSectionsCallToActionActionLinkFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomeSectionsCallToActionFilter = {
  headline?: InputMaybe<StringFilter>;
  actionLink?: InputMaybe<HomeSectionsCallToActionActionLinkFilter>;
};

export type HomeSectionsTestimonialsCustomersFilter = {
  name?: InputMaybe<StringFilter>;
  job?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
  testimonial?: InputMaybe<StringFilter>;
};

export type HomeSectionsTestimonialsFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  customers?: InputMaybe<HomeSectionsTestimonialsCustomersFilter>;
};

export type HomeSectionsProjectsFilter = {
  title?: InputMaybe<StringFilter>;
};

export type HomeSectionsPostsFilter = {
  title?: InputMaybe<StringFilter>;
};

export type HomeSectionsFilter = {
  Hero?: InputMaybe<HomeSectionsHeroFilter>;
  Marquee?: InputMaybe<HomeSectionsMarqueeFilter>;
  Feature?: InputMaybe<HomeSectionsFeatureFilter>;
  Services?: InputMaybe<HomeSectionsServicesFilter>;
  CallToAction?: InputMaybe<HomeSectionsCallToActionFilter>;
  Testimonials?: InputMaybe<HomeSectionsTestimonialsFilter>;
  Projects?: InputMaybe<HomeSectionsProjectsFilter>;
  Posts?: InputMaybe<HomeSectionsPostsFilter>;
};

export type HomeFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  sections?: InputMaybe<HomeSectionsFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type PagesSeoImage = {
  __typename?: 'PagesSeoImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PagesSeo = {
  __typename?: 'PagesSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<PagesSeoImage>;
};

export type PagesSectionsHero = {
  __typename?: 'PagesSectionsHero';
  headline?: Maybe<Scalars['String']['output']>;
  subHeadline?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsFeatureItems = {
  __typename?: 'PagesSectionsFeatureItems';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  fimage?: Maybe<Scalars['String']['output']>;
};

export type PagesSectionsFeature = {
  __typename?: 'PagesSectionsFeature';
  items?: Maybe<Array<Maybe<PagesSectionsFeatureItems>>>;
};

export type PagesSections = PagesSectionsHero | PagesSectionsFeature;

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  mainImage?: Maybe<Scalars['String']['output']>;
  seo?: Maybe<PagesSeo>;
  sections?: Maybe<Array<Maybe<PagesSections>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesSeoImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PagesSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<PagesSeoImageFilter>;
};

export type PagesSectionsHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  subHeadline?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type PagesSectionsFeatureItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  fimage?: InputMaybe<ImageFilter>;
};

export type PagesSectionsFeatureFilter = {
  items?: InputMaybe<PagesSectionsFeatureItemsFilter>;
};

export type PagesSectionsFilter = {
  hero?: InputMaybe<PagesSectionsHeroFilter>;
  feature?: InputMaybe<PagesSectionsFeatureFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  mainImage?: InputMaybe<ImageFilter>;
  seo?: InputMaybe<PagesSeoFilter>;
  sections?: InputMaybe<PagesSectionsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  publishDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type Projects = Node & Document & {
  __typename?: 'Projects';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  publishDate?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectsConnectionEdges = {
  __typename?: 'ProjectsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Projects>;
};

export type ProjectsConnection = Connection & {
  __typename?: 'ProjectsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectsConnectionEdges>>>;
};

export type GlobalImage = {
  __typename?: 'GlobalImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type GlobalNavLinks = {
  __typename?: 'GlobalNavLinks';
  text?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type GlobalFooterNavLinks = {
  __typename?: 'GlobalFooterNavLinks';
  text?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type GlobalSocialLinks = {
  __typename?: 'GlobalSocialLinks';
  text?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type GlobalSubscribe = {
  __typename?: 'GlobalSubscribe';
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  formUrl?: Maybe<Scalars['String']['output']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<GlobalImage>;
  navLinks?: Maybe<Array<Maybe<GlobalNavLinks>>>;
  footerNavLinks?: Maybe<Array<Maybe<GlobalFooterNavLinks>>>;
  socialLinks?: Maybe<Array<Maybe<GlobalSocialLinks>>>;
  subscribe?: Maybe<GlobalSubscribe>;
  postsPerPage?: Maybe<Scalars['Float']['output']>;
  projectsPerPage?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalImageFilter = {
  src?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type GlobalNavLinksFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GlobalFooterNavLinksFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GlobalSocialLinksFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type GlobalSubscribeFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  formUrl?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type GlobalFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<GlobalImageFilter>;
  navLinks?: InputMaybe<GlobalNavLinksFilter>;
  footerNavLinks?: InputMaybe<GlobalFooterNavLinksFilter>;
  socialLinks?: InputMaybe<GlobalSocialLinksFilter>;
  subscribe?: InputMaybe<GlobalSubscribeFilter>;
  postsPerPage?: InputMaybe<NumberFilter>;
  projectsPerPage?: InputMaybe<NumberFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type ThemeFonts = {
  __typename?: 'ThemeFonts';
  sans?: Maybe<Scalars['String']['output']>;
  serif?: Maybe<Scalars['String']['output']>;
};

export type ThemeLetterSpacing = {
  __typename?: 'ThemeLetterSpacing';
  tight?: Maybe<Scalars['String']['output']>;
};

export type ThemeColors = {
  __typename?: 'ThemeColors';
  primary?: Maybe<Scalars['String']['output']>;
  secondary?: Maybe<Scalars['String']['output']>;
  background?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type ThemeSpacing = {
  __typename?: 'ThemeSpacing';
  sm?: Maybe<Scalars['String']['output']>;
  md?: Maybe<Scalars['String']['output']>;
  lg?: Maybe<Scalars['String']['output']>;
  xs?: Maybe<Scalars['String']['output']>;
};

export type ThemeTypography = {
  __typename?: 'ThemeTypography';
  fontFamily?: Maybe<Scalars['String']['output']>;
  fontSize?: Maybe<Scalars['String']['output']>;
  lineHeight?: Maybe<Scalars['String']['output']>;
};

export type Theme = Node & Document & {
  __typename?: 'Theme';
  fonts?: Maybe<ThemeFonts>;
  letterSpacing?: Maybe<ThemeLetterSpacing>;
  colors?: Maybe<ThemeColors>;
  spacing?: Maybe<ThemeSpacing>;
  typography?: Maybe<ThemeTypography>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ThemeFontsFilter = {
  sans?: InputMaybe<StringFilter>;
  serif?: InputMaybe<StringFilter>;
};

export type ThemeLetterSpacingFilter = {
  tight?: InputMaybe<StringFilter>;
};

export type ThemeColorsFilter = {
  primary?: InputMaybe<StringFilter>;
  secondary?: InputMaybe<StringFilter>;
  background?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type ThemeSpacingFilter = {
  sm?: InputMaybe<StringFilter>;
  md?: InputMaybe<StringFilter>;
  lg?: InputMaybe<StringFilter>;
  xs?: InputMaybe<StringFilter>;
};

export type ThemeTypographyFilter = {
  fontFamily?: InputMaybe<StringFilter>;
  fontSize?: InputMaybe<StringFilter>;
  lineHeight?: InputMaybe<StringFilter>;
};

export type ThemeFilter = {
  fonts?: InputMaybe<ThemeFontsFilter>;
  letterSpacing?: InputMaybe<ThemeLetterSpacingFilter>;
  colors?: InputMaybe<ThemeColorsFilter>;
  spacing?: InputMaybe<ThemeSpacingFilter>;
  typography?: InputMaybe<ThemeTypographyFilter>;
};

export type ThemeConnectionEdges = {
  __typename?: 'ThemeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Theme>;
};

export type ThemeConnection = Connection & {
  __typename?: 'ThemeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ThemeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updatePages: Pages;
  createPages: Pages;
  updateBlog: Blog;
  createBlog: Blog;
  updateProjects: Projects;
  createProjects: Projects;
  updateGlobal: Global;
  createGlobal: Global;
  updateTheme: Theme;
  createTheme: Theme;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationCreateProjectsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectsMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateThemeArgs = {
  relativePath: Scalars['String']['input'];
  params: ThemeMutation;
};


export type MutationCreateThemeArgs = {
  relativePath: Scalars['String']['input'];
  params: ThemeMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  pages?: InputMaybe<PagesMutation>;
  blog?: InputMaybe<BlogMutation>;
  projects?: InputMaybe<ProjectsMutation>;
  global?: InputMaybe<GlobalMutation>;
  theme?: InputMaybe<ThemeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  pages?: InputMaybe<PagesMutation>;
  blog?: InputMaybe<BlogMutation>;
  projects?: InputMaybe<ProjectsMutation>;
  global?: InputMaybe<GlobalMutation>;
  theme?: InputMaybe<ThemeMutation>;
};

export type HomeSectionsHeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subHeadline?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsMarqueeItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsMarqueeMutation = {
  items?: InputMaybe<Array<InputMaybe<HomeSectionsMarqueeItemsMutation>>>;
};

export type HomeSectionsFeatureItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  fimage?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsFeatureMutation = {
  items?: InputMaybe<Array<InputMaybe<HomeSectionsFeatureItemsMutation>>>;
};

export type HomeSectionsServicesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  serviceImage?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subTitle?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeSectionsServicesItemsMutation>>>;
};

export type HomeSectionsCallToActionActionLinkMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsCallToActionMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  actionLink?: InputMaybe<HomeSectionsCallToActionActionLinkMutation>;
};

export type HomeSectionsTestimonialsCustomersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  job?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  testimonial?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsTestimonialsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  customers?: InputMaybe<Array<InputMaybe<HomeSectionsTestimonialsCustomersMutation>>>;
};

export type HomeSectionsProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsPostsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
};

export type HomeSectionsMutation = {
  Hero?: InputMaybe<HomeSectionsHeroMutation>;
  Marquee?: InputMaybe<HomeSectionsMarqueeMutation>;
  Feature?: InputMaybe<HomeSectionsFeatureMutation>;
  Services?: InputMaybe<HomeSectionsServicesMutation>;
  CallToAction?: InputMaybe<HomeSectionsCallToActionMutation>;
  Testimonials?: InputMaybe<HomeSectionsTestimonialsMutation>;
  Projects?: InputMaybe<HomeSectionsProjectsMutation>;
  Posts?: InputMaybe<HomeSectionsPostsMutation>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<HomeSectionsMutation>>>;
};

export type PagesSeoImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<PagesSeoImageMutation>;
};

export type PagesSectionsHeroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subHeadline?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsFeatureItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  fimage?: InputMaybe<Scalars['String']['input']>;
};

export type PagesSectionsFeatureMutation = {
  items?: InputMaybe<Array<InputMaybe<PagesSectionsFeatureItemsMutation>>>;
};

export type PagesSectionsMutation = {
  hero?: InputMaybe<PagesSectionsHeroMutation>;
  feature?: InputMaybe<PagesSectionsFeatureMutation>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  mainImage?: InputMaybe<Scalars['String']['input']>;
  seo?: InputMaybe<PagesSeoMutation>;
  sections?: InputMaybe<Array<InputMaybe<PagesSectionsMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GlobalImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalNavLinksMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalFooterNavLinksMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalSocialLinksMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalSubscribeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  formUrl?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<GlobalImageMutation>;
  navLinks?: InputMaybe<Array<InputMaybe<GlobalNavLinksMutation>>>;
  footerNavLinks?: InputMaybe<Array<InputMaybe<GlobalFooterNavLinksMutation>>>;
  socialLinks?: InputMaybe<Array<InputMaybe<GlobalSocialLinksMutation>>>;
  subscribe?: InputMaybe<GlobalSubscribeMutation>;
  postsPerPage?: InputMaybe<Scalars['Float']['input']>;
  projectsPerPage?: InputMaybe<Scalars['Float']['input']>;
};

export type ThemeFontsMutation = {
  sans?: InputMaybe<Scalars['String']['input']>;
  serif?: InputMaybe<Scalars['String']['input']>;
};

export type ThemeLetterSpacingMutation = {
  tight?: InputMaybe<Scalars['String']['input']>;
};

export type ThemeColorsMutation = {
  primary?: InputMaybe<Scalars['String']['input']>;
  secondary?: InputMaybe<Scalars['String']['input']>;
  background?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ThemeSpacingMutation = {
  sm?: InputMaybe<Scalars['String']['input']>;
  md?: InputMaybe<Scalars['String']['input']>;
  lg?: InputMaybe<Scalars['String']['input']>;
  xs?: InputMaybe<Scalars['String']['input']>;
};

export type ThemeTypographyMutation = {
  fontFamily?: InputMaybe<Scalars['String']['input']>;
  fontSize?: InputMaybe<Scalars['String']['input']>;
  lineHeight?: InputMaybe<Scalars['String']['input']>;
};

export type ThemeMutation = {
  fonts?: InputMaybe<ThemeFontsMutation>;
  letterSpacing?: InputMaybe<ThemeLetterSpacingMutation>;
  colors?: InputMaybe<ThemeColorsMutation>;
  spacing?: InputMaybe<ThemeSpacingMutation>;
  typography?: InputMaybe<ThemeTypographyMutation>;
};

export type HomePartsFragment = { __typename: 'Home', title: string, description?: string | null, sections?: Array<{ __typename: 'HomeSectionsHero', headline?: string | null, subHeadline?: string | null, image?: string | null } | { __typename: 'HomeSectionsMarquee', items?: Array<{ __typename: 'HomeSectionsMarqueeItems', title?: string | null } | null> | null } | { __typename: 'HomeSectionsFeature', items?: Array<{ __typename: 'HomeSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | { __typename: 'HomeSectionsServices', title?: string | null, subTitle?: string | null, image?: string | null, items?: Array<{ __typename: 'HomeSectionsServicesItems', title?: string | null, description?: string | null, serviceImage?: string | null } | null> | null } | { __typename: 'HomeSectionsCallToAction', headline?: string | null, actionLink?: { __typename: 'HomeSectionsCallToActionActionLink', text?: string | null, href?: string | null } | null } | { __typename: 'HomeSectionsTestimonials', title?: string | null, image?: string | null, customers?: Array<{ __typename: 'HomeSectionsTestimonialsCustomers', name?: string | null, job?: string | null, avatar?: string | null, testimonial?: string | null } | null> | null } | { __typename: 'HomeSectionsProjects', title?: string | null } | { __typename: 'HomeSectionsPosts', title?: string | null } | null> | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, mainImage?: string | null, body?: any | null, seo?: { __typename: 'PagesSeo', title?: string | null, description?: string | null, image?: { __typename: 'PagesSeoImage', src?: string | null, alt?: string | null } | null } | null, sections?: Array<{ __typename: 'PagesSectionsHero', headline?: string | null, subHeadline?: string | null, text?: string | null } | { __typename: 'PagesSectionsFeature', items?: Array<{ __typename: 'PagesSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | null> | null };

export type BlogPartsFragment = { __typename: 'Blog', title: string, excerpt?: string | null, publishDate?: string | null, body?: any | null };

export type ProjectsPartsFragment = { __typename: 'Projects', title: string, description?: string | null, publishDate?: string | null, body?: any | null };

export type GlobalPartsFragment = { __typename: 'Global', title: string, subtitle?: string | null, description?: string | null, postsPerPage?: number | null, projectsPerPage?: number | null, image?: { __typename: 'GlobalImage', src?: string | null, alt?: string | null } | null, navLinks?: Array<{ __typename: 'GlobalNavLinks', text?: string | null, href?: string | null } | null> | null, footerNavLinks?: Array<{ __typename: 'GlobalFooterNavLinks', text?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'GlobalSocialLinks', text?: string | null, href?: string | null } | null> | null, subscribe?: { __typename: 'GlobalSubscribe', title?: string | null, text?: string | null, formUrl?: string | null } | null };

export type ThemePartsFragment = { __typename: 'Theme', fonts?: { __typename: 'ThemeFonts', sans?: string | null, serif?: string | null } | null, letterSpacing?: { __typename: 'ThemeLetterSpacing', tight?: string | null } | null, colors?: { __typename: 'ThemeColors', primary?: string | null, secondary?: string | null, background?: string | null, text?: string | null } | null, spacing?: { __typename: 'ThemeSpacing', sm?: string | null, md?: string | null, lg?: string | null, xs?: string | null } | null, typography?: { __typename: 'ThemeTypography', fontFamily?: string | null, fontSize?: string | null, lineHeight?: string | null } | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'HomeSectionsHero', headline?: string | null, subHeadline?: string | null, image?: string | null } | { __typename: 'HomeSectionsMarquee', items?: Array<{ __typename: 'HomeSectionsMarqueeItems', title?: string | null } | null> | null } | { __typename: 'HomeSectionsFeature', items?: Array<{ __typename: 'HomeSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | { __typename: 'HomeSectionsServices', title?: string | null, subTitle?: string | null, image?: string | null, items?: Array<{ __typename: 'HomeSectionsServicesItems', title?: string | null, description?: string | null, serviceImage?: string | null } | null> | null } | { __typename: 'HomeSectionsCallToAction', headline?: string | null, actionLink?: { __typename: 'HomeSectionsCallToActionActionLink', text?: string | null, href?: string | null } | null } | { __typename: 'HomeSectionsTestimonials', title?: string | null, image?: string | null, customers?: Array<{ __typename: 'HomeSectionsTestimonialsCustomers', name?: string | null, job?: string | null, avatar?: string | null, testimonial?: string | null } | null> | null } | { __typename: 'HomeSectionsProjects', title?: string | null } | { __typename: 'HomeSectionsPosts', title?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, title: string, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'HomeSectionsHero', headline?: string | null, subHeadline?: string | null, image?: string | null } | { __typename: 'HomeSectionsMarquee', items?: Array<{ __typename: 'HomeSectionsMarqueeItems', title?: string | null } | null> | null } | { __typename: 'HomeSectionsFeature', items?: Array<{ __typename: 'HomeSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | { __typename: 'HomeSectionsServices', title?: string | null, subTitle?: string | null, image?: string | null, items?: Array<{ __typename: 'HomeSectionsServicesItems', title?: string | null, description?: string | null, serviceImage?: string | null } | null> | null } | { __typename: 'HomeSectionsCallToAction', headline?: string | null, actionLink?: { __typename: 'HomeSectionsCallToActionActionLink', text?: string | null, href?: string | null } | null } | { __typename: 'HomeSectionsTestimonials', title?: string | null, image?: string | null, customers?: Array<{ __typename: 'HomeSectionsTestimonialsCustomers', name?: string | null, job?: string | null, avatar?: string | null, testimonial?: string | null } | null> | null } | { __typename: 'HomeSectionsProjects', title?: string | null } | { __typename: 'HomeSectionsPosts', title?: string | null } | null> | null } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, mainImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PagesSeo', title?: string | null, description?: string | null, image?: { __typename: 'PagesSeoImage', src?: string | null, alt?: string | null } | null } | null, sections?: Array<{ __typename: 'PagesSectionsHero', headline?: string | null, subHeadline?: string | null, text?: string | null } | { __typename: 'PagesSectionsFeature', items?: Array<{ __typename: 'PagesSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, mainImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo?: { __typename: 'PagesSeo', title?: string | null, description?: string | null, image?: { __typename: 'PagesSeoImage', src?: string | null, alt?: string | null } | null } | null, sections?: Array<{ __typename: 'PagesSectionsHero', headline?: string | null, subHeadline?: string | null, text?: string | null } | { __typename: 'PagesSectionsFeature', items?: Array<{ __typename: 'PagesSectionsFeatureItems', title?: string | null, text?: string | null, fimage?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, excerpt?: string | null, publishDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, excerpt?: string | null, publishDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjectsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectsQuery = { __typename?: 'Query', projects: { __typename: 'Projects', id: string, title: string, description?: string | null, publishDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectsFilter>;
}>;


export type ProjectsConnectionQuery = { __typename?: 'Query', projectsConnection: { __typename?: 'ProjectsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectsConnectionEdges', cursor: string, node?: { __typename: 'Projects', id: string, title: string, description?: string | null, publishDate?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, title: string, subtitle?: string | null, description?: string | null, postsPerPage?: number | null, projectsPerPage?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'GlobalImage', src?: string | null, alt?: string | null } | null, navLinks?: Array<{ __typename: 'GlobalNavLinks', text?: string | null, href?: string | null } | null> | null, footerNavLinks?: Array<{ __typename: 'GlobalFooterNavLinks', text?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'GlobalSocialLinks', text?: string | null, href?: string | null } | null> | null, subscribe?: { __typename: 'GlobalSubscribe', title?: string | null, text?: string | null, formUrl?: string | null } | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, title: string, subtitle?: string | null, description?: string | null, postsPerPage?: number | null, projectsPerPage?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'GlobalImage', src?: string | null, alt?: string | null } | null, navLinks?: Array<{ __typename: 'GlobalNavLinks', text?: string | null, href?: string | null } | null> | null, footerNavLinks?: Array<{ __typename: 'GlobalFooterNavLinks', text?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'GlobalSocialLinks', text?: string | null, href?: string | null } | null> | null, subscribe?: { __typename: 'GlobalSubscribe', title?: string | null, text?: string | null, formUrl?: string | null } | null } | null } | null> | null } };

export type ThemeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ThemeQuery = { __typename?: 'Query', theme: { __typename: 'Theme', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, fonts?: { __typename: 'ThemeFonts', sans?: string | null, serif?: string | null } | null, letterSpacing?: { __typename: 'ThemeLetterSpacing', tight?: string | null } | null, colors?: { __typename: 'ThemeColors', primary?: string | null, secondary?: string | null, background?: string | null, text?: string | null } | null, spacing?: { __typename: 'ThemeSpacing', sm?: string | null, md?: string | null, lg?: string | null, xs?: string | null } | null, typography?: { __typename: 'ThemeTypography', fontFamily?: string | null, fontSize?: string | null, lineHeight?: string | null } | null } };

export type ThemeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ThemeFilter>;
}>;


export type ThemeConnectionQuery = { __typename?: 'Query', themeConnection: { __typename?: 'ThemeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ThemeConnectionEdges', cursor: string, node?: { __typename: 'Theme', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, fonts?: { __typename: 'ThemeFonts', sans?: string | null, serif?: string | null } | null, letterSpacing?: { __typename: 'ThemeLetterSpacing', tight?: string | null } | null, colors?: { __typename: 'ThemeColors', primary?: string | null, secondary?: string | null, background?: string | null, text?: string | null } | null, spacing?: { __typename: 'ThemeSpacing', sm?: string | null, md?: string | null, lg?: string | null, xs?: string | null } | null, typography?: { __typename: 'ThemeTypography', fontFamily?: string | null, fontSize?: string | null, lineHeight?: string | null } | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  title
  description
  sections {
    __typename
    ... on HomeSectionsHero {
      headline
      subHeadline
      image
    }
    ... on HomeSectionsMarquee {
      items {
        __typename
        title
      }
    }
    ... on HomeSectionsFeature {
      items {
        __typename
        title
        text
        fimage
      }
    }
    ... on HomeSectionsServices {
      title
      subTitle
      image
      items {
        __typename
        title
        description
        serviceImage
      }
    }
    ... on HomeSectionsCallToAction {
      headline
      actionLink {
        __typename
        text
        href
      }
    }
    ... on HomeSectionsTestimonials {
      title
      image
      customers {
        __typename
        name
        job
        avatar
        testimonial
      }
    }
    ... on HomeSectionsProjects {
      title
    }
    ... on HomeSectionsPosts {
      title
    }
  }
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  mainImage
  seo {
    __typename
    title
    description
    image {
      __typename
      src
      alt
    }
  }
  sections {
    __typename
    ... on PagesSectionsHero {
      headline
      subHeadline
      text
    }
    ... on PagesSectionsFeature {
      items {
        __typename
        title
        text
        fimage
      }
    }
  }
  body
}
    `;
export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  excerpt
  publishDate
  body
}
    `;
export const ProjectsPartsFragmentDoc = gql`
    fragment ProjectsParts on Projects {
  __typename
  title
  description
  publishDate
  body
}
    `;
export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  title
  subtitle
  description
  image {
    __typename
    src
    alt
  }
  navLinks {
    __typename
    text
    href
  }
  footerNavLinks {
    __typename
    text
    href
  }
  socialLinks {
    __typename
    text
    href
  }
  subscribe {
    __typename
    title
    text
    formUrl
  }
  postsPerPage
  projectsPerPage
}
    `;
export const ThemePartsFragmentDoc = gql`
    fragment ThemeParts on Theme {
  __typename
  fonts {
    __typename
    sans
    serif
  }
  letterSpacing {
    __typename
    tight
  }
  colors {
    __typename
    primary
    secondary
    background
    text
  }
  spacing {
    __typename
    sm
    md
    lg
    xs
  }
  typography {
    __typename
    fontFamily
    fontSize
    lineHeight
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const ProjectsDocument = gql`
    query projects($relativePath: String!) {
  projects(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectsParts
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const ProjectsConnectionDocument = gql`
    query projectsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectsFilter) {
  projectsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectsParts
      }
    }
  }
}
    ${ProjectsPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const ThemeDocument = gql`
    query theme($relativePath: String!) {
  theme(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ThemeParts
  }
}
    ${ThemePartsFragmentDoc}`;
export const ThemeConnectionDocument = gql`
    query themeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ThemeFilter) {
  themeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ThemeParts
      }
    }
  }
}
    ${ThemePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    projects(variables: ProjectsQueryVariables, options?: C): Promise<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}> {
        return requester<{data: ProjectsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsQueryVariables, query: string}, ProjectsQueryVariables>(ProjectsDocument, variables, options);
      },
    projectsConnection(variables?: ProjectsConnectionQueryVariables, options?: C): Promise<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectsConnectionQueryVariables, query: string}, ProjectsConnectionQueryVariables>(ProjectsConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    theme(variables: ThemeQueryVariables, options?: C): Promise<{data: ThemeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThemeQueryVariables, query: string}> {
        return requester<{data: ThemeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThemeQueryVariables, query: string}, ThemeQueryVariables>(ThemeDocument, variables, options);
      },
    themeConnection(variables?: ThemeConnectionQueryVariables, options?: C): Promise<{data: ThemeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThemeConnectionQueryVariables, query: string}> {
        return requester<{data: ThemeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ThemeConnectionQueryVariables, query: string}, ThemeConnectionQueryVariables>(ThemeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  